# Generated by Django 2.2 on 2019-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20190416_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
